### ISSUE TITLE
Missing ld symbols on Arch Linux when runnning "/bin/ls" under SaBRe

### ISSUE THREAD

**Issue by RiscInside** [srg-imperial/SaBRe#86]
I am trying to get `./sabre plugins/sbr-trace/libsbr-trace.so -- /bin/ls` to work on Arch Linux. I am getting this error:
```
sabre: /home/notiurii/Uni/UROP2/SaBRe/loader/rewriter.c:562: find_ld_symbol: Assertion `false && "We couldn't find ld symbols"' failed.
fish: Job 1, './sabre plugins/sbr-trace/libsb…' terminated by signal SIGABRT (Abort)
```
How do I approach this issue? See full log at https://www.toptal.com/developers/hastebin/conexaqoku.log

**Comment by andronat** [comment]
Ah! This is because we have the loader debug symbol paths hard coded [here](https://github.com/srg-imperial/SaBRe/blob/master/loader/rewriter.c#L546-L549). In Ubuntu ld debug symbols are installed through `libc6-dbg`, you need to check where Arch stores its own.

Ideally, and if you really want to make an important contribution, you can find a way to infer the debug symbol position automatically in some general way. e.g. like GDB does. I'm not sure what's the right approach here though. Maybe the ld elf file has some pointers about the correct path of the debug symbols, or maybe there are some standard linux directories that these debug symbols are expected (e.g. `/usr/lib/debug/lib/x86_64-linux-gnu/`). But I'm not sure. Nevertheless, an automated way would be highly appreciated!

Also, a low hanging fruit would also be to generalize the current code into automatically finding the right `.so` file in `/usr/lib/debug/lib/x86_64-linux-gnu/`. We currently only have 2 hard coded paths, but what happens if we have `ld-2.32.so` etc?

**Comment by RiscInside** [comment]
Funnily enough, `/usr/lib/debug/lib/x86_64-linux-gnu/` does not even exist on my system. In my PR (#87), I have opted for a slightly more nuclear option: downloading the debug info using `debuginfod`. There is a high chance GDB can search in other locations as well, but I didn't manage to find what these places are.

**Comment by RiscInside** [comment]
With recent changes in #87, debuginfod is no longer required
